version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: matchmaking-postgres
    environment:
      POSTGRES_USER: matchmaking_user
      POSTGRES_PASSWORD: matchmaking_password
      POSTGRES_DB: matchmaking_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

